SET SERVEROUTPUT ON;

SELECT BASECONVERSION.Bin2Dec('00101')
FROM DUAL;

SELECT BASECONVERSION.Dec2Bin(32)
FROM DUAL;

SELECT BASECONVERSION.Dec2Hex(127)
FROM DUAL;

SELECT BASECONVERSION.Dec2Hex(0)
FROM DUAL;