SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET TIMING ON;

CREATE OR REPLACE
PACKAGE COMPANIESHOUSE 
AS
    
    FUNCTION COMPANY(gRegistrationID IN VARCHAR2)
    RETURN CLOB;
    
    FUNCTION SEARCH_COMPANIES
    (
        gText IN VARCHAR2,
        gItemsPerPage IN INTEGER DEFAULT NULL,
        gStartIndex IN INTEGER DEFAULT NULL
    )
    RETURN CLOB;
    
    PROCEDURE IMPORT_COMPANY(gRegistrationID IN VARCHAR2);
    
END;
/