CREATE OR REPLACE 
TYPE T_EMAIL_ATTACHMENTS
AS
OBJECT
(
    LIST T_ATTACHMENTS,
    
    CONSTRUCTOR FUNCTION T_EMAIL_ATTACHMENTS RETURN SELF AS RESULT,
    
    MEMBER PROCEDURE ATTACHED_FILE
    (
        FileName IN VARCHAR2,
        ContentType IN VARCHAR2,
        File IN CLOB
    ),
    
    STATIC FUNCTION ATTACHED_FILE
    (
        FileName IN VARCHAR2,
        ContentType IN VARCHAR2,
        File IN CLOB
    )
    RETURN T_EMAIL_ATTACHMENTS
);