CREATE OR REPLACE
VIEW FULLYEARLY$FXRATE
AS
SELECT From$Currency_ID,
To$Currency_ID,
EXTRACT(YEAR FROM DateX) AS Year,
AVG(Rate) AS Rate
FROM FULLDAILY$FXRATE
GROUP BY From$Currency_ID,
To$Currency_ID,
EXTRACT(YEAR FROM DateX)
WITH READ ONLY;

/*
--test
SELECT *
FROM FULLYEARLY$FXRATE
WHERE From$Currency_ID = 'USD'
AND To$Currency_ID = 'GBP'
AND Year = 2008;
*/