CREATE OR REPLACE
VIEW FULLMONTHLY$FXRATE
AS
SELECT From$Currency_ID,
To$Currency_ID,
EXTRACT(YEAR FROM DateX) AS Year,
EXTRACT(MONTH FROM DateX) AS Month,
AVG(Rate) AS Rate
FROM FULLDAILY$FXRATE
GROUP BY From$Currency_ID,
To$Currency_ID,
EXTRACT(YEAR FROM DateX),
EXTRACT(MONTH FROM DateX)
WITH READ ONLY;

/*
--test
SELECT *
FROM FULLMONTHLY$FXRATE
WHERE From$Currency_ID = 'USD'
AND To$Currency_ID = 'GBP'
AND Year = 2008
AND Month = 7;
*/