CREATE OR REPLACE
VIEW OBJECTMEASUREMENT
(
    ID,
    MEASUREMENTMETHOD_ID,
    MEASUREMENTUNIT_ID,
    OBJECT_ID,
    PERSON_ID,
    QUANTITY_ID,
    NAME,
    NUMBERDATAPOINT,
    NUMERICALQUANTITYVALUE,
    STANDARDMEASUREMENTUNCERTAINTY,
    UUID,
    DATETIMESTART,
    DATETIMEEND,
    DATETIMECREATED,
    DATETIMEDELETED,
    COMMENTS,
    CONSTRAINT OBJECTMEASUREMENT_PK PRIMARY KEY (ID) RELY DISABLE NOVALIDATE
)
AS
SELECT /*+ FIRST_ROWS */
A.ID,
B.MeasurementMethod_ID,
D.MeasurementUnit_ID,
E.Object_ID,
G.Person_ID,
B.Quantity_ID,
A.Name,
C.NumberDataPoint,
D.NumericalQuantityValue,
C.StandardMeasurementUncertainty,
A.UUID,
A.DateTimeStart,
A.DateTimeEnd,
A.DateTimeCreated,
A.DateTimeDeleted,
A.Comments
FROM EVENT A
INNER JOIN MEASUREMENT B
    ON A.ID = B.Event_ID
INNER JOIN MEASUREMENTRESULT C
    ON B.Event_ID = C.Event_ID
INNER JOIN MEASUREDQUANTITYVALUE D
    ON C.ID = D.MeasurementResult_ID
INNER JOIN EVENT#OBJECT E
    ON A.ID = E.Event_ID
INNER JOIN EVENTTOOBJECTTYPE F
    ON E.EventToObjectType_ID = F.ID
LEFT OUTER JOIN EVENT#PERSON G
    ON A.ID = G.Event_ID
LEFT OUTER JOIN EVENTTOPERSONTYPE H
    ON G.EventToPersonType_ID = H.ID
            AND 'Creator' = H.Name
WHERE F.Name = 'Measured Object';

/*
--test
SELECT *
FROM OBJECTMEASUREMENT
WHERE Object_ID = 1;
*/