--DROP TABLE ABFULLSIZEIMAGE PURGE;
--hex gets an extra CHR(10) at end, hence need LRTRIM
CREATE
TABLE ABFULLSIZEIMAGE
(
    RECORD_ID INTEGER,
    CROP_X INTEGER,
    CROP_Y INTEGER,
    CROP_WIDTH INTEGER,
    DATA_ CLOB
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        READSIZE 16777216
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ABFULLSIZEIMAGE.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            RECORD_ID INTEGER EXTERNAL(255),
            CROP_X INTEGER EXTERNAL(255),
            CROP_Y INTEGER EXTERNAL(255),
            CROP_WIDTH INTEGER EXTERNAL(255),
            DATA_ CHAR(16777216)
        )
    )
    LOCATION('cd6702cea29fe89cf280a76794405adb17f9a0ee')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT Record_ID,
Crop_X,
Crop_Y,
Crop_Width,
--Data_,
CLOB_IN_HEX_TO_BLOB(Data_) AS BLOB$Data_,
CASE DBMS_LOB.SubStr
(
    BLOB_TO_CLOB
    (
        TO_BLOB
        (
            HEXTORAW
            (
                DBMS_LOB.SubStr(Data_, 16, 1)
            )
        )
    ),
    4,
    1
)
    WHEN '�PNG' THEN 'image/png'
    WHEN '���J' THEN 'image/jpeg'
    ELSE NULL
END AS ContentType
FROM ABFULLSIZEIMAGE
WHERE Record_ID = 120;
*/