--DROP TABLE ABMULTIVALUEENTRY PURGE;
CREATE
TABLE ABMULTIVALUEENTRY
(
    PARENT_ID INTEGER,
    KEY INTEGER,
    VALUE VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ABMULTIVALUEENTRY.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            PARENT_ID INTEGER EXTERNAL(255),
            KEY INTEGER EXTERNAL(255),
            VALUE CHAR(4000)
        )
    )
    LOCATION('31bb7ba8914766d4ba40d6dfb6113c8b614be442')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT Parent_ID,
Key,
REPLACE(Value, '\0A', CHR(10)) AS Value
FROM ABMULTIVALUEENTRY;

SELECT A.Value,
COUNT(*)
FROM ABMULTIVALUEENTRY A
INNER JOIN ABMULTIVALUEENTRYKEY B
    ON A.Key = B.RowID_
WHERE B.Value = 'service'
AND UPPER(A.Value) NOT IN
(
    SELECT UPPER(Name)
    FROM COMMUNICATIONTYPE
)
GROUP BY A.Value
ORDER BY 2 DESC
;
*/