--DROP TABLE ABPERSON PURGE;
CREATE
TABLE ABPERSON
(
    ROWID_ INTEGER,
    FIRST_ VARCHAR2(4000 BYTE),
    LAST VARCHAR2(4000 BYTE),
    MIDDLE VARCHAR2(4000 BYTE),
    FIRSTPHONETIC VARCHAR2(4000 BYTE),
    MIDDLEPHONETIC VARCHAR2(4000 BYTE),
    LASTPHONETIC VARCHAR2(4000 BYTE),
    ORGANIZATION VARCHAR2(4000 BYTE),
    DEPARTMENT VARCHAR2(4000 BYTE),
    NOTE VARCHAR2(4000 BYTE),
    KIND INTEGER,
    BIRTHDAY VARCHAR2(4000 BYTE),
    JOBTITLE VARCHAR2(4000 BYTE),
    NICKNAME VARCHAR2(4000 BYTE),
    PREFIX VARCHAR2(4000 BYTE),
    SUFFIX VARCHAR2(4000 BYTE),
    FIRSTSORT CLOB,
    LASTSORT CLOB,
    CREATIONDATE INTEGER,
    MODIFICATIONDATE INTEGER,
    COMPOSITENAMEFALLBACK VARCHAR2(4000 BYTE),
    EXTERNALIDENTIFIER VARCHAR2(4000 BYTE),
    EXTERNALMODIFICATIONTAG VARCHAR2(4000 BYTE),
    EXTERNALUUID VARCHAR2(4000 BYTE),
    STOREID INTEGER,
    DISPLAYNAME VARCHAR2(4000 BYTE),
    EXTERNALREPRESENTATION VARCHAR2(4000 BYTE),
    FIRSTSORTSECTION VARCHAR2(4000 BYTE),
    LASTSORTSECTION VARCHAR2(4000 BYTE),
    FIRSTSORTLANGUAGEINDEX INTEGER,
    LASTSORTLANGUAGEINDEX INTEGER,
    PERSONLINK INTEGER,
    IMAGEURI VARCHAR2(4000 BYTE),
    ISPREFERREDNAME INTEGER,
    GUID VARCHAR2(4000 BYTE),
    PHONEMEDATA VARCHAR2(4000 BYTE),
    ALTERNATEBIRTHDAY VARCHAR2(4000 BYTE),
    MAPSDATA VARCHAR2(4000 BYTE),
    FIRSTPRONUNCIATION VARCHAR2(4000 BYTE),
    MIDDLEPRONUNCIATION VARCHAR2(4000 BYTE),
    LASTPRONUNCIATION VARCHAR2(4000 BYTE),
    ORGANIZATIONPHONETIC VARCHAR2(4000 BYTE),
    ORGANIZATIONPRONUNCIATION VARCHAR2(4000 BYTE),
    PREVIOUSFAMILYNAME VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ABPERSON.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ROWID_ INTEGER EXTERNAL(255),
            FIRST_ CHAR(4000),
            "LAST" CHAR(4000),
            MIDDLE CHAR(4000),
            FIRSTPHONETIC CHAR(4000),
            MIDDLEPHONETIC CHAR(4000),
            LASTPHONETIC CHAR(4000),
            "ORGANIZATION" CHAR(4000),
            DEPARTMENT CHAR(4000),
            NOTE CHAR(4000),
            KIND INTEGER EXTERNAL(255),
            BIRTHDAY CHAR(4000),
            JOBTITLE CHAR(4000),
            NICKNAME CHAR(4000),
            PREFIX CHAR(4000),
            "SUFFIX" CHAR(4000),
            FIRSTSORT CHAR(32767),
            LASTSORT CHAR(32767),
            CREATIONDATE INTEGER EXTERNAL(255),
            MODIFICATIONDATE INTEGER EXTERNAL(255),
            COMPOSITENAMEFALLBACK CHAR(4000),
            EXTERNALIDENTIFIER CHAR(4000),
            EXTERNALMODIFICATIONTAG CHAR(4000),
            EXTERNALUUID CHAR(4000),
            STOREID INTEGER EXTERNAL(255),
            DISPLAYNAME CHAR(4000),
            EXTERNALREPRESENTATION CHAR(4000),
            FIRSTSORTSECTION CHAR(4000),
            LASTSORTSECTION CHAR(4000),
            FIRSTSORTLANGUAGEINDEX INTEGER EXTERNAL(255),
            LASTSORTLANGUAGEINDEX INTEGER EXTERNAL(255),
            PERSONLINK INTEGER EXTERNAL(255),
            IMAGEURI CHAR(4000),
            ISPREFERREDNAME INTEGER EXTERNAL(255),
            GUID CHAR(4000),
            PHONEMEDATA CHAR(4000),
            ALTERNATEBIRTHDAY CHAR(4000),
            MAPSDATA CHAR(4000),
            FIRSTPRONUNCIATION CHAR(4000),
            MIDDLEPRONUNCIATION CHAR(4000),
            LASTPRONUNCIATION CHAR(4000),
            ORGANIZATIONPHONETIC CHAR(4000),
            ORGANIZATIONPRONUNCIATION CHAR(4000),
            PREVIOUSFAMILYNAME CHAR(4000)
        )
    )
    LOCATION('31bb7ba8914766d4ba40d6dfb6113c8b614be442')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM ABPERSON;
*/