--DROP TABLE S_GEONAMESPOSTALCODE PURGE;
CREATE
TABLE S_GEONAMESPOSTALCODE
(
    COUNTRYCODE VARCHAR2(2 BYTE),
    POSTALCODE VARCHAR2(20 BYTE),
    PLACENAME VARCHAR2(180 BYTE),
    ADMINNAME1 VARCHAR2(100 BYTE),
    ADMINCODE1 VARCHAR2(20 BYTE),
    ADMINNAME2 VARCHAR2(100 BYTE),
    ADMINCODE2 VARCHAR2(20 BYTE),
    ADMINNAME3 VARCHAR2(100 BYTE),
    ADMINCODE4 VARCHAR2(20 BYTE),
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    ACCURACY NUMBER(1)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'unzip.sh'
        FIELDS TERMINATED BY 0X'09'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            COUNTRYCODE CHAR(2),
            POSTALCODE CHAR(20),
            PLACENAME CHAR(180),
            ADMINNAME1 CHAR(100),
            ADMINCODE1 CHAR(20),
            ADMINNAME2 CHAR(100),
            ADMINCODE2 CHAR(20),
            ADMINNAME3 CHAR(100),
            ADMINCODE4 CHAR(20),
            LATITUDE CHAR,
            LONGITUDE CHAR,
            ACCURACY CHAR(1)
        )
    )
    LOCATION('S_GEONAMESPOSTALCODE.zip')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 1
;

/*
--test
SELECT *
FROM S_GEONAMESPOSTALCODE
WHERE CountryCode = 'IE';

SELECT CountryCode,
PostalCode,
PlaceName
FROM S_GEONAMESPOSTALCODE
GROUP BY CountryCode,
PostalCode,
PlaceName
HAVING COUNT(*) > 1;

SELECT *
FROM S_GEONAMESPOSTALCODE
WHERE CountryCode = 'AT'
AND PostalCode = '9461';
*/