--DROP TABLE S_GEONAMESALTNAME_D PURGE;
CREATE
TABLE S_GEONAMESALTNAME_D
(
    ALTERNATENAMEID INTEGER,
    GEONAMESID INTEGER,
    COMMENTS VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ALTERNATENAMEID INTEGER EXTERNAL(255),
            GEONAMESID INTEGER EXTERNAL(255),
            COMMENTS CHAR(4000)
        )
    )
    LOCATION ('S_GEONAMESALTNAME_D.tsv')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;