--DROP TABLE S_GEONAMESALTNAME PURGE;
CREATE
TABLE S_GEONAMESALTNAME
(
    ALTERNATENAMEID INTEGER,
    GEONAMEID INTEGER,
    ISOLANGUAGE VARCHAR2(7 BYTE),
    ALTERNATENAME VARCHAR2(200 CHAR),
    ISPREFERREDNAME NUMBER(1),
    ISSHORTNAME NUMBER(1),
    ISCOLLOQUIAL NUMBER(1),
    ISHISTORIC NUMBER(1)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'unzip_S_GEONAMESALTNAME.sh'
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ALTERNATENAMEID INTEGER EXTERNAL(255),
            GEONAMEID INTEGER EXTERNAL(255),
            ISOLANGUAGE CHAR(7),
            ALTERNATENAME CHAR(800),
            ISPREFERREDNAME CHAR(1),
            ISSHORTNAME CHAR(1),
            ISCOLLOQUIAL CHAR(1),
            ISHISTORIC CHAR(1)
        )
    )
    LOCATION('alternateNames.zip')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 1
;

/*
--test
SELECT *
FROM S_GEONAMESALTNAME
WHERE AlternateName != TRIM(AlternateName);
*/