--DROP TABLE S_GEONAMESFEATURECODE PURGE;
CREATE
TABLE S_GEONAMESFEATURECODE 
(
    ID VARCHAR2(7 BYTE),
    NAME VARCHAR2(100 BYTE),
    COMMENTS VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ID CHAR(7),
            NAME CHAR(100),
            COMMENTS CHAR(4000)
        )
    )
    LOCATION ('S_GEONAMESFEATURECODE.tsv')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;