--DROP TABLE E$ISO_639_3_RETIREMENTS PURGE;
CREATE
TABLE E$ISO_639_3_RETIREMENTS
(
    ID CHAR(3 BYTE),
    REF_NAME VARCHAR2(150 BYTE),
    RET_REASON CHAR(1 BYTE),
    CHANGE_TO CHAR(3 BYTE),
    RET_REMEDY VARCHAR2(300 BYTE),
    EFFECTIVE DATE
)
ORGANIZATION EXTERNAL 
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 1
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ID CHAR(3),
            REF_NAME CHAR(150),
            RET_REASON CHAR(1),
            CHANGE_TO CHAR(3),
            RET_REMEDY CHAR(300),
            EFFECTIVE CHAR DATE_FORMAT DATE MASK "YYYY-MM-DD"
        )
    )
    LOCATION('iso-639-3_Retirements.tab')
)
NOPARALLEL
NOMONITORING
;