--DROP TABLE E$ISO15924 PURGE;
CREATE
TABLE E$ISO15924
(
    ID CHAR(4 BYTE),
    NUMERICCODE CHAR(3 BYTE),
    NAME VARCHAR2(100 BYTE),
    NAMEFRENCH VARCHAR2(100 CHAR),
    PROPERTYVALUEALIAS VARCHAR2(100 CHAR),
    UNICODEVERSION NUMBER,
    DATEMODIFIED DATE
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 7
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY ';'
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ID CHAR (4),
            NUMERICCODE CHAR(3),
            NAME CHAR(100),
            NAMEFRENCH CHAR(400),
            PROPERTYVALUEALIAS CHAR(400),
            UNICODEVERSION CHAR,
            DATEMODIFIED CHAR DATE_FORMAT DATE MASK "YYYY-MM-DD"
        )
    )
    LOCATION('iso15924.txt')
)
NOPARALLEL
NOMONITORING
;

/*
--test
SELECT *
FROM E$ISO15924;
*/