--DROP TABLE E$ISO_639_3_MACROLANGUAGES PURGE;
CREATE
TABLE E$ISO_639_3_MACROLANGUAGES
(
    M_ID CHAR(3 BYTE),
    I_ID CHAR(3 BYTE),
    I_STATUS CHAR(1 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0D0A'
        SKIP 1
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            M_ID CHAR(3),
            I_ID CHAR(3),
            I_STATUS CHAR(1)
        )
    )
    LOCATION('iso-639-3-macrolanguages.tab')
)
NOPARALLEL
NOMONITORING
;