--DROP TABLE S_ISO639_3RETIREMENTS PURGE;
--SKIP 1 leaves last character of last line, so use REJECT LIMIT 1 instead
CREATE
TABLE S_ISO639_3RETIREMENTS
(
    ID CHAR(3 BYTE),
    REF_NAME VARCHAR2(150 BYTE),
    RET_REASON CHAR(1 BYTE),
    CHANGE_TO CHAR(3 BYTE),
    RET_REMEDY VARCHAR2(300 BYTE),
    EFFECTIVE DATE
)
ORGANIZATION EXTERNAL 
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ID CHAR(3),
            REF_NAME CHAR(150),
            RET_REASON CHAR(1),
            CHANGE_TO CHAR(3),
            RET_REMEDY CHAR(300),
            EFFECTIVE CHAR DATE_FORMAT DATE MASK "YYYY-MM-DD"
        )
    )
    LOCATION('S_ISO639_3RETIREMENTS.tab')
)
NOPARALLEL
NOMONITORING
REJECT LIMIT 1
;