--DROP TABLE E$ISO_639_3_NAME_INDEX PURGE;
CREATE
TABLE E$ISO_639_3_NAME_INDEX
(
    ID CHAR(3 BYTE),
    PRINT_NAME VARCHAR2(75 BYTE),
    INVERTED_NAME VARCHAR2(75 BYTE)
)
ORGANIZATION EXTERNAL 
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0D0A'
        SKIP 1
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ID CHAR(3),
            PRINT_NAME CHAR(75),
            INVERTED_NAME CHAR(75)
        )
    )
    LOCATION('iso-639-3_Name_Index.tab')
)
NOPARALLEL
NOMONITORING
;