--DROP TABLE E$MICROSOFTSTORESUPPORTEDLANGUAGES PURGE;
CREATE
TABLE E$MICROSOFTSTORESUPPORTEDLANGUAGES
(
    LANGUAGE_NAME VARCHAR2(255 BYTE),
    SUPPORTED_LANGUAGE_CODES VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 1
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            LANGUAGE_NAME CHAR,
            SUPPORTED_LANGUAGE_CODES CHAR(4000) LRTRIM
        )
    )
    LOCATION ('List of supported languages for Microsoft Store.csv')
)
NOPARALLEL
NOMONITORING
;