--DROP TABLE S_NANP PURGE;
--Note that the date is in two digit form in the source, so that the date conversion may fail e.g. leap year FEB
CREATE
TABLE S_NANP
(
    ID	NUMBER(3,0),
    EASILYRECOGNISABLE	VARCHAR2(100 BYTE),
    ASSIGNABLE	VARCHAR2(3 BYTE),
    ASSIGNABLEEXPLANATION	VARCHAR2(100 BYTE),
    RESERVED	VARCHAR2(3 BYTE),
    ASSIGNED	VARCHAR2(3 BYTE),
    ASSIGNEDDATE	DATE,
    GEOGRAPHIC	CHAR(1 BYTE),
    COUNTRYSUBDIV_NAME VARCHAR2(100 BYTE),
    COUNTRY_NAME VARCHAR2(100 BYTE),
    INSERVICE	VARCHAR2(3 BYTE),
    INSERVICEDATE	DATE,
    STATUS	VARCHAR2(100 BYTE),
    PLANNINGLETTERNUMBERS VARCHAR2(100 BYTE),
    --
    OVERLAY	VARCHAR2(3 BYTE),
    OVERLAYCOMPLEX	VARCHAR2(100 BYTE),
    PARENT_NANP_ID	NUMBER(3,0),
    ASSIGNEDSERVICE	VARCHAR2(100 BYTE),
    "TIMEZONE"	VARCHAR2(10 BYTE),
    --
    "MAP"	VARCHAR2(100 BYTE),
    JEOPARDY	VARCHAR2(3 BYTE),
    RELIEFPLANNINGINPROGRESS	VARCHAR2(3 BYTE),
    HOMETOLOCAL	VARCHAR2(10 BYTE),
    HOMETOTOLL	VARCHAR2(10 BYTE),
    FOREIGNTOLOCAL	VARCHAR2(10 BYTE),
    FOREIGNTOTOLL	VARCHAR2(10 BYTE),
    HOMETOLOCALPERM	VARCHAR2(10 BYTE),
    HOMETOTOLLPERM	VARCHAR2(10 BYTE),
    FOREIGNTOLOCALPERM	VARCHAR2(10 BYTE),
    COMMENTS	VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        REJECT ROWS WITH ALL NULL FIELDS
        (
            "ID" CHAR(3),
            EASILYRECOGNISABLE	CHAR(100),
            ASSIGNABLE	CHAR(3),
            ASSIGNABLEEXPLANATION	CHAR(100),
            RESERVED	CHAR(3),
            ASSIGNED	CHAR(3),
            ASSIGNEDDATE	CHAR(10) DATE_FORMAT DATE MASK "DD-MON-RR",
            GEOGRAPHIC	CHAR(1),
            COUNTRYSUBDIV_NAME CHAR(100),
            COUNTRY_NAME CHAR(100),
            INSERVICE	CHAR(3),
            INSERVICEDATE	CHAR(10) DATE_FORMAT DATE MASK "DD-MON-RR",
            STATUS	CHAR(100),
            PLANNINGLETTERNUMBERS CHAR(100),
            FILLER CHAR(32767),
            OVERLAY	CHAR(3),
            OVERLAYCOMPLEX	CHAR(100),
            PARENT_NANP_ID	CHAR(3),
            ASSIGNEDSERVICE	CHAR(100),
            "TIMEZONE"	CHAR(10),
            FILLER CHAR(32767),
            "MAP"	CHAR(100),
            JEOPARDY	CHAR(3),
            RELIEFPLANNINGINPROGRESS	CHAR(3),
            HOMETOLOCAL	CHAR(10),
            HOMETOTOLL	CHAR(10),
            FOREIGNTOLOCAL	CHAR(10),
            FOREIGNTOTOLL	CHAR(10),
            HOMETOLOCALPERM	CHAR(10),
            HOMETOTOLLPERM	CHAR(10),
            FOREIGNTOLOCALPERM	CHAR(10),
            COMMENTS	CHAR(4000)
        )
    )
    LOCATION ('S_NANP.csv')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;