--DROP TABLE S_UNLOCODE PURGE;
CREATE
TABLE S_UNLOCODE
(
    CHANGE VARCHAR2(1 BYTE),
    COUNTRY VARCHAR2(2 BYTE),
    LOCATION VARCHAR2(3 BYTE),
    NAME VARCHAR2(100 CHAR),
    NAMEWODIACRITICS VARCHAR2(100 CHAR),
    SUBDIVISION VARCHAR2(3 BYTE),
    FUNCTION VARCHAR2(8 BYTE),
    STATUS VARCHAR2(2 BYTE),
    DATEX DATE,
    IATA VARCHAR2(3 BYTE),
    COORDINATES VARCHAR2(13 BYTE),
    REMARKS VARCHAR2(100 CHAR)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET WE8ISO8859P1
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'unzip_S_UNLOCODE.sh'
        FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            CHANGE CHAR(1),
            COUNTRY CHAR(2),
            LOCATION CHAR(3),
            NAME CHAR(400),
            NAMEWODIACRITICS CHAR(400),
            SUBDIVISION CHAR(3),
            FUNCTION CHAR(8),
            STATUS CHAR(2),
            DATEX CHAR DATE_FORMAT DATE MASK "RRMM",
            IATA CHAR(3),
            COORDINATES CHAR(13),
            REMARKS CHAR(100) LRTRIM
        )
    )
    LOCATION
    (
        'loc*csv.zip'
    )
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 1
;

/*
--test
SELECT *
FROM S_UNLOCODE;
*/