--DROP TABLE S_UNICODEINDEX PURGE;
CREATE
TABLE S_UNICODEINDEX
(
    NAME	VARCHAR2(100 BYTE),
    CODEPOINT	VARCHAR2(6 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 0
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09' OPTIONALLY ENCLOSED BY '"'
        REJECT ROWS WITH ALL NULL FIELDS
        (
            NAME	CHAR(100),
            CODEPOINT	CHAR(6)
        )
    )
    LOCATION ('S_UNICODEINDEX.txt')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;

/*
--test
SELECT COUNT(*)
FROM S_UNICODEINDEX
;
*/