--DROP TABLE S_USDANNDSR_NUTR_DEF PURGE;
CREATE
TABLE S_USDANNDSR_NUTR_DEF
(
    NUTR_NO VARCHAR2(3 BYTE),
    UNITS VARCHAR2(7 BYTE),
    TAGNAME VARCHAR2(20 BYTE),
    NUTRDESC VARCHAR2(60 BYTE),
    NUM_DEC CHAR(1 BYTE),
    SR_ORDER NUMBER(6)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET WE8ISO8859P1
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY '^' OPTIONALLY ENCLOSED BY '~' LRTRIM
        (
            NUTR_NO CHAR(3),
            UNITS CHAR(7),
            TAGNAME CHAR(20),
            NUTRDESC CHAR(60),
            NUM_DEC CHAR(1),
            SR_ORDER INTEGER EXTERNAL(6)
        )
    )
    LOCATION('S_USDANNDSR_NUTR_DEF.txt')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT Nutr_No,
Units,
Tagname,
NutrDesc,
Num_Dec,
SR_Order
FROM S_USDANNDSR_NUTR_DEF;
*/
