--DROP TABLE IMSG$ATTACHMENT PURGE;
CREATE
TABLE IMSG$ATTACHMENT
(
    ROWID_ INTEGER,
    GUID CHAR(36 BYTE),
    CREATED_DATE INTEGER,
    START_DATE INTEGER,
    FILENAME VARCHAR2(4000 BYTE),
    UTI VARCHAR2(4000 BYTE),
    MIME_TYPE VARCHAR2(4000 BYTE),
    TRANSFER_STATE INTEGER,
    IS_OUTGOING INTEGER,
    USER_INFO CLOB,
    TRANSFER_NAME VARCHAR2(4000 BYTE),
    TOTAL_BYTES INTEGER
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'IMSG$ATTACHMENT.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ROWID_ INTEGER EXTERNAL(255),
            GUID CHAR(36),
            CREATED_DATE INTEGER EXTERNAL(255),
            START_DATE INTEGER EXTERNAL(255),
            FILENAME CHAR(4000),
            UTI CHAR(4000),
            MIME_TYPE CHAR(4000),
            TRANSFER_STATE INTEGER EXTERNAL(255),
            IS_OUTGOING INTEGER EXTERNAL(255),
            USER_INFO CHAR(1048576),
            TRANSFER_NAME CHAR(4000),
            TOTAL_BYTES INTEGER EXTERNAL(255)
        )
    )
    LOCATION('3d0d7e5fb2ce288813306e4d4636395e047a3d28')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM IMSG$ATTACHMENT;
*/