--DROP TABLE IMSG$HANDLE PURGE;
CREATE
TABLE IMSG$HANDLE
(
    ROWID_ INTEGER,
    ID VARCHAR2(100 BYTE),
    COUNTRY VARCHAR2(2 BYTE),
    SERVICE VARCHAR2(100 BYTE),
    UNCANONICALIZED_ID VARCHAR2(100 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'IMSG$HANDLE.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ROWID_ INTEGER EXTERNAL(255),
            ID CHAR(100),
            COUNTRY CHAR(2),
            SERVICE CHAR(100),
            UNCANONICALIZED_ID CHAR(100)
        )
    )
    LOCATION('3d0d7e5fb2ce288813306e4d4636395e047a3d28')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM IMSG$HANDLE;
*/