--DROP TABLE IMSG$MESSAGE PURGE;
CREATE
TABLE IMSG$MESSAGE
(
    ROWID_ INTEGER,
    GUID CHAR(36 BYTE),
    TEXT VARCHAR2(4000 BYTE),
    REPLACE_ INTEGER,
    SERVICE_CENTER VARCHAR2(4000 BYTE),
    HANDLE_ID INTEGER,
    SUBJECT VARCHAR2(4000 BYTE),
    COUNTRY VARCHAR2(4000 BYTE),
    ATTRIBUTEDBODY CLOB,
    VERSION INTEGER,
    TYPE INTEGER,
    SERVICE VARCHAR2(4000 BYTE),
    ACCOUNT VARCHAR2(4000 BYTE),
    ACCOUNT_GUID VARCHAR2(4000 BYTE),
    ERROR INTEGER,
    DATE_ INTEGER,
    DATE_READ INTEGER,
    DATE_DELIVERED INTEGER,
    IS_DELIVERED INTEGER,
    IS_FINISHED INTEGER,
    IS_EMOTE INTEGER,
    IS_FROM_ME INTEGER,
    IS_EMPTY INTEGER,
    IS_DELAYED INTEGER,
    IS_AUTO_REPLY INTEGER,
    IS_PREPARED INTEGER,
    IS_READ INTEGER,
    IS_SYSTEM_MESSAGE INTEGER,
    IS_SENT INTEGER,
    HAS_DD_RESULTS INTEGER,
    IS_SERVICE_MESSAGE INTEGER,
    IS_FORWARD INTEGER,
    WAS_DOWNGRADED INTEGER,
    IS_ARCHIVE INTEGER,
    CACHE_HAS_ATTACHMENTS INTEGER,
    CACHE_ROOMNAMES VARCHAR2(4000 BYTE),
    WAS_DATA_DETECTED INTEGER,
    WAS_DEDUPLICATED INTEGER,
    IS_AUDIO_MESSAGE INTEGER,
    IS_PLAYED INTEGER,
    DATE_PLAYED INTEGER,
    ITEM_TYPE INTEGER,
    OTHER_HANDLE INTEGER,
    GROUP_TITLE VARCHAR2(4000 BYTE),
    GROUP_ACTION_TYPE INTEGER,
    SHARE_STATUS INTEGER,
    SHARE_DIRECTION INTEGER,
    IS_EXPIRABLE INTEGER,
    EXPIRE_STATE INTEGER,
    MESSAGE_ACTION_TYPE INTEGER,
    MESSAGE_SOURCE INTEGER
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'IMSG$MESSAGE.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ROWID_ CHAR,
            GUID CHAR(36),
            TEXT CHAR(4000),
            REPLACE_ CHAR,
            SERVICE_CENTER CHAR(4000),
            HANDLE_ID CHAR,
            SUBJECT CHAR(4000),
            COUNTRY CHAR(4000),
            ATTRIBUTEDBODY CHAR(1048576),
            VERSION CHAR,
            TYPE CHAR,
            SERVICE CHAR(4000),
            ACCOUNT CHAR(4000),
            ACCOUNT_GUID CHAR(4000),
            ERROR CHAR,
            DATE_ CHAR,
            DATE_READ CHAR,
            DATE_DELIVERED CHAR,
            IS_DELIVERED CHAR,
            IS_FINISHED CHAR,
            IS_EMOTE CHAR,
            IS_FROM_ME CHAR,
            IS_EMPTY CHAR,
            IS_DELAYED CHAR,
            IS_AUTO_REPLY CHAR,
            IS_PREPARED CHAR,
            IS_READ CHAR,
            IS_SYSTEM_MESSAGE CHAR,
            IS_SENT CHAR,
            HAS_DD_RESULTS CHAR,
            IS_SERVICE_MESSAGE CHAR,
            IS_FORWARD CHAR,
            WAS_DOWNGRADED CHAR,
            IS_ARCHIVE CHAR,
            CACHE_HAS_ATTACHMENTS CHAR,
            CACHE_ROOMNAMES CHAR(4000),
            WAS_DATA_DETECTED CHAR,
            WAS_DEDUPLICATED CHAR,
            IS_AUDIO_MESSAGE CHAR,
            IS_PLAYED CHAR,
            DATE_PLAYED CHAR,
            ITEM_TYPE CHAR,
            OTHER_HANDLE CHAR,
            GROUP_TITLE CHAR(4000),
            GROUP_ACTION_TYPE CHAR,
            SHARE_STATUS CHAR,
            SHARE_DIRECTION CHAR,
            IS_EXPIRABLE CHAR,
            EXPIRE_STATE CHAR,
            MESSAGE_ACTION_TYPE CHAR,
            MESSAGE_SOURCE CHAR
        )
    )
    LOCATION('3d0d7e5fb2ce288813306e4d4636395e047a3d28')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM IMSG$MESSAGE
WHERE INSTR(Text, '\0A') > 0;
*/