--DROP TABLE IMSG$MESSAGE_ATTACHMENT_JOIN PURGE;
--Attachment_ID has rogue newline e.g.'"347
--", so need LRTRIM
CREATE
TABLE IMSG$MESSAGE_ATTACHMENT_JOIN
(
    MESSAGE_ID INTEGER,
    ATTACHMENT_ID INTEGER
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'IMSG$MESSAGE_ATTACHMENT_JOIN.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        LRTRIM
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            MESSAGE_ID INTEGER EXTERNAL(255),
            ATTACHMENT_ID INTEGER EXTERNAL(255)
        )
    )
    LOCATION('3d0d7e5fb2ce288813306e4d4636395e047a3d28')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM IMSG$MESSAGE_ATTACHMENT_JOIN;
*/