--DROP TABLE S_23ANDME_GENOME PURGE;
CREATE
TABLE S_23ANDME_GENOME
(
    RSSID VARCHAR2(16 BYTE),
    CHROMOSOME VARCHAR2(2 BYTE),
    "POSITION" INTEGER,
    GENOTYPE VARCHAR2(2 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 20
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            RSSID CHAR(16),
            CHROMOSOME CHAR(2),
            "POSITION" INTEGER EXTERNAL(16),
            GENOTYPE CHAR(2) LRTRIM
        )
    )
    LOCATION ('S_23ANDME_GENOME.txt')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;

/*
--test
SELECT *
FROM S_23ANDME_GENOME
--WHERE Chromosome = 'X'
WHERE RSSID = 'rs53576'
;
*/