/*
Use REJECT LIMIT 1 instead of SKIP 1, as that causes
KUP-04038: internal error: invalid position for sequential file
KUP-04017: OS message: Error 0
KUP-04118: operation "pos_seq", location "skudmip:1"
*/
--DROP TABLE S_CHD PURGE;
CREATE
TABLE S_CHD
(
    GEOGCD CHAR(9 BYTE),
    GEOGNM VARCHAR2(200 BYTE),
    GEOGNMW VARCHAR2(100 BYTE),
    SI_ID VARCHAR2(9 BYTE),
    SI_TITLE VARCHAR2(255 BYTE),
    OPER_DATE DATE,
    TERM_DATE DATE,
    PARENTCD CHAR(9 BYTE),
    ENTITYCD CHAR(3 BYTE),
    OWNER VARCHAR2(100 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET WE8ISO8859P1
        STRING SIZES ARE IN BYTES
        NOBADFILE NOLOGFILE NODISCARDFILE
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'unzip_S_CHD.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            GEOGCD CHAR(9),
            GEOGNM CHAR(200),
            GEOGNMW CHAR(100),
            SI_ID CHAR(9),
            SI_TITLE CHAR(255),
            OPER_DATE CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY HH24:MI:SS",
            TERM_DATE CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY HH24:MI:SS",
            PARENTCD CHAR(9),
            ENTITYCD CHAR(3),
            OWNER CHAR(100) LRTRIM
        )
    )
    LOCATION('Code_History_Database*.zip')
)
NOPARALLEL
NOMONITORING
REJECT LIMIT 1
;

/*
--test
SELECT COUNT(*)
FROM S_CHD;
*/