--DROP TABLE S_COUNTRYINFO PURGE;
CREATE TABLE S_COUNTRYINFO
(
    ALPHA2 CHAR(2 BYTE),
    ALPHA3 CHAR(3 BYTE),
    ID INTEGER,
    FIPS CHAR(2 BYTE),
    NAME VARCHAR2(256 CHAR),
    CAPITAL VARCHAR2(256 CHAR),
    AREA INTEGER,
    POPULATION INTEGER,
    CONTINENT CHAR(2 BYTE),
    TLD VARCHAR2(256 CHAR),
    CURRENCYCODE CHAR(3 BYTE),
    CURRENCYNAME VARCHAR2(256 CHAR),
    PHONE VARCHAR2(256 CHAR),
    POSTALCODEFORMAT VARCHAR2(256 CHAR),
    POSTALCODEREGEX VARCHAR2(256 CHAR),
    LANGUAGES VARCHAR2(256 CHAR),
    GEONAMEID INTEGER,
    NEIGHBOURS VARCHAR2(256 CHAR),
    EQUIVALENTFIPS CHAR(2 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        SKIP 51
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ALPHA2 CHAR(2),
            ALPHA3 CHAR(3),
            ID INTEGER EXTERNAL(255),
            FIPS CHAR(2),
            NAME CHAR(1024),
            CAPITAL CHAR(1024),
            AREA INTEGER EXTERNAL(255),
            POPULATION INTEGER EXTERNAL(255),
            CONTINENT CHAR(2),
            TLD CHAR(1024),
            CURRENCYCODE CHAR(3),
            CURRENCYNAME CHAR(1024),
            PHONE CHAR(1024),
            POSTALCODEFORMAT CHAR(1024),
            POSTALCODEREGEX CHAR(1024),
            LANGUAGES CHAR(1024),
            GEONAMEID INTEGER EXTERNAL(255),
            NEIGHBOURS CHAR(1024),
            EQUIVALENTFIPS CHAR(2) LRTRIM
        )
    )
    LOCATION ('S_COUNTRYINFO.txt')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;