--DROP TABLE S_GEONAMESALTNAME_M PURGE;
CREATE
TABLE S_GEONAMESALTNAME_M
(
    ALTERNATENAMEID INTEGER,
    GEONAMEID INTEGER,
    ISOLANGUAGE VARCHAR2(7 BYTE),
    ALTERNATENAME VARCHAR2(200 CHAR),
    ISPREFERREDNAME NUMBER(1),
    ISSHORTNAME NUMBER(1),
    ISCOLLOQUIAL NUMBER(1),
    ISHISTORIC NUMBER(1)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            ALTERNATENAMEID INTEGER EXTERNAL(255),
            GEONAMEID INTEGER EXTERNAL(255),
            ISOLANGUAGE CHAR(7),
            ALTERNATENAME CHAR(800),
            ISPREFERREDNAME CHAR(1),
            ISSHORTNAME CHAR(1),
            ISCOLLOQUIAL CHAR(1),
            ISHISTORIC CHAR(1)
        )
    )
    LOCATION ('S_GEONAMESALTNAME_M.tsv')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;