--DROP TABLE S_GEONAMES_D PURGE;
CREATE
TABLE S_GEONAMES_D 
(
    GEONAMESID INTEGER,
    NAME VARCHAR2(200 CHAR),
    COMMENTS VARCHAR2(1000 CHAR)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY 0X'09'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            GEONAMESID INTEGER EXTERNAL(255),
            NAME CHAR(800),
            COMMENTS CHAR(4000)
        )
    )
    LOCATION ('S_GEONAMES_D.tsv')
)
PARALLEL
NOMONITORING
--REJECT LIMIT 1
;