--DROP TABLE S_LIFEEXPECTANCY_FEMALE PURGE;
--SKIP 1 doesn't work, using REJECT LIMIT 3 (as extra rows at the bottom)
CREATE
TABLE S_LIFEEXPECTANCY_FEMALE 
(
    TIME INTEGER,
    TIME_CODE VARCHAR2(6 BYTE),
    COUNTRY_NAME VARCHAR2(100 BYTE),
    COUNTRY_ID CHAR(3 BYTE),
    VALUE VARCHAR2(18 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            "TIME" INTEGER EXTERNAL(4),
            TIME_CODE CHAR(6),
            COUNTRY_NAME CHAR(100),
            COUNTRY_ID CHAR(3),
            VALUE CHAR(18) LRTRIM
        )
    )
    LOCATION ('S_LIFEEXPECTANCY_FEMALE.csv')
)
NOPARALLEL
NOMONITORING
REJECT LIMIT 3
;