--DROP TABLE S_USDANNDSR_NUT_DATA PURGE;
CREATE
TABLE S_USDANNDSR_NUT_DATA
(
    NDB_NO VARCHAR2(5 BYTE),
    NUTR_NO VARCHAR2(3 BYTE),
    NUTR_VAL NUMBER(13, 3),
    NUM_DATA_PTS NUMBER(5),
    STD_ERROR NUMBER(11, 3),
    SRC_CD VARCHAR2(2 BYTE),
    DERIV_CD VARCHAR2(4 BYTE),
    REF_NDB_NO VARCHAR2(5 BYTE),
    ADD_NUTR_MARK CHAR(1 BYTE),
    NUM_STUDIES NUMBER(2),
    MIN NUMBER(13, 3),
    MAX NUMBER(13, 3),
    DF NUMBER(4),
    LOW_EB NUMBER(13, 3),
    UP_EB NUMBER(13, 3),
    STAT_CMT VARCHAR2(10 BYTE),
    ADDMOD_DATE DATE,
    CC CHAR(1 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET WE8ISO8859P1
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY '^' OPTIONALLY ENCLOSED BY '~' LRTRIM
        (
            NDB_NO CHAR(5),
            NUTR_NO CHAR(3),
            NUTR_VAL DECIMAL EXTERNAL(13),
            NUM_DATA_PTS INTEGER EXTERNAL(5),
            STD_ERROR DECIMAL EXTERNAL(11),
            SRC_CD CHAR(2),
            DERIV_CD CHAR(4),
            REF_NDB_NO CHAR(5),
            ADD_NUTR_MARK CHAR(1),
            NUM_STUDIES INTEGER EXTERNAL(2),
            MIN DECIMAL EXTERNAL(13),
            MAX DECIMAL EXTERNAL(13),
            DF INTEGER EXTERNAL(4),
            LOW_EB DECIMAL EXTERNAL(13),
            UP_EB DECIMAL EXTERNAL(13),
            STAT_CMT CHAR(10),
            ADDMOD_DATE CHAR(10) DATE_FORMAT DATE MASK "MM/YYYY",
            CC CHAR(1)
        )
    )
    LOCATION('S_USDANNDSR_NUT_DATA.txt')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT NDB_No,
Nutr_No,
Nutr_Val,
Num_Data_Pts,
Std_Error,
Src_Cd,
Deriv_Cd,
Ref_NDB_No,
Add_Nutr_Mark,
Num_Studies,
Min,
Max,
DF,
Low_EB,
Up_EB,
Stat_Cmt,
AddMod_Date,
CC
FROM S_USDANNDSR_NUT_DATA;
*/
