--DROP TABLE S_USDANNDSR_FD_GROUP PURGE;
CREATE
TABLE S_USDANNDSR_FD_GROUP
(
    FDGRP_CD VARCHAR2(4 BYTE),
    FDGRP_DESC VARCHAR2(60 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY RD
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY 0X'0A'
        CHARACTERSET WE8ISO8859P1
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        FIELDS TERMINATED BY '^' OPTIONALLY ENCLOSED BY '~' LRTRIM
        (
            FDGRP_CD CHAR(4),
            FDGRP_DESC CHAR(60)
        )
    )
    LOCATION('S_USDANNDSR_FD_GROUP.txt')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT FdGrp_Cd,
FdGrp_Desc
FROM S_USDANNDSR_FD_GROUP;
*/
