--DROP TABLE ZKIKATTACHMENT PURGE;
CREATE
TABLE ZKIKATTACHMENT
(
    Z_PK INTEGER,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZFLAGS INTEGER,
    ZINTERNALID INTEGER,
    ZRETRYCOUNT INTEGER,
    ZSTATE INTEGER,
    ZTYPE INTEGER,
    ZEXTRA INTEGER,
    ZMESSAGE INTEGER,
    ZLASTACCESSTIMESTAMP INTEGER,
    ZTIMESTAMP INTEGER,
    ZCONTENT VARCHAR2(4000 BYTE)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ZKIKATTACHMENT.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            Z_PK CHAR,
            Z_ENT CHAR,
            Z_OPT CHAR,
            ZFLAGS CHAR,
            ZINTERNALID CHAR,
            ZRETRYCOUNT CHAR,
            ZSTATE CHAR,
            ZTYPE CHAR,
            ZEXTRA CHAR,
            ZMESSAGE CHAR,
            ZLASTACCESSTIMESTAMP CHAR,
            ZTIMESTAMP CHAR,
            ZCONTENT CHAR(4000)
        )
    )
    LOCATION('8e281be6657d4523710d96341b6f86ba89b56df7')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM ZKIKATTACHMENT;
*/