--DROP TABLE ZKIKMESSAGE PURGE;
CREATE
TABLE ZKIKMESSAGE
(
    Z_PK INTEGER,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZFLAGS INTEGER,
    ZINTERNALID INTEGER,
    ZSTATE INTEGER,
    ZSYSTEMSTATE INTEGER,
    ZTYPE INTEGER,
    ZCHATEXTRA INTEGER,
    ZDRAFTMESSAGECHAT INTEGER,
    ZEXTRA INTEGER,
    ZLASTMESSAGECHAT INTEGER,
    ZLASTMESSAGEUSER INTEGER,
    ZUSER INTEGER,
    ZRECEIVEDTIMESTAMP INTEGER,
    ZTIMESTAMP INTEGER,
    ZBODY VARCHAR2(4000 BYTE),
    ZSTANZAID VARCHAR2(4000 BYTE),
    ZRENDERINSTRUCTIONSET CLOB
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ZKIKMESSAGE.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            Z_PK CHAR,
            Z_ENT CHAR,
            Z_OPT CHAR,
            ZFLAGS CHAR,
            ZINTERNALID CHAR,
            ZSTATE CHAR,
            ZSYSTEMSTATE CHAR,
            ZTYPE CHAR,
            ZCHATEXTRA CHAR,
            ZDRAFTMESSAGECHAT CHAR,
            ZEXTRA CHAR,
            ZLASTMESSAGECHAT CHAR,
            ZLASTMESSAGEUSER CHAR,
            ZUSER CHAR,
            ZRECEIVEDTIMESTAMP CHAR,
            ZTIMESTAMP CHAR,
            ZBODY CHAR(4000),
            ZSTANZAID CHAR(4000),
            ZRENDERINSTRUCTIONSET CHAR(1048576)
        )
    )
    LOCATION('8e281be6657d4523710d96341b6f86ba89b56df7')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM ZKIKMESSAGE
WHERE ZUSER = 8;
*/