--DROP TABLE ZKIKUSER PURGE;
CREATE
TABLE ZKIKUSER
(
    Z_PK INTEGER,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZADDRESSBOOKID INTEGER,
    ZFLAGS INTEGER,
    ZINTERNALID INTEGER,
    ZPRESENCE INTEGER,
    ZTYPE INTEGER,
    ZCHATUSER INTEGER,
    ZEXTRA INTEGER,
    ZLASTMESSAGE INTEGER,
    ZDISPLAYNAME VARCHAR2(4000 BYTE),
    ZDISPLAYNAMEASCII VARCHAR2(4000 BYTE),
    ZEMAIL VARCHAR2(4000 BYTE),
    ZFIRSTNAME VARCHAR2(4000 BYTE),
    ZGROUPTAG VARCHAR2(4000 BYTE),
    ZJID VARCHAR2(4000 BYTE),
    ZLASTNAME VARCHAR2(4000 BYTE),
    ZPPTIMESTAMP VARCHAR2(4000 BYTE),
    ZPPURL VARCHAR2(4000 BYTE),
    ZSTATUS VARCHAR2(4000 BYTE),
    ZUSERNAME VARCHAR2(4000 BYTE),
    ZCONTENTLINKSPROTODATA CLOB
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY SQLITE
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        SKIP 2
        CHARACTERSET UTF8
        NOBADFILE NOLOGFILE NODISCARDFILE
        STRING SIZES ARE IN BYTES
        DISABLE_DIRECTORY_LINK_CHECK
        PREPROCESSOR EXE:'ZKIKUSER.sh'
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
        REJECT ROWS WITH ALL NULL FIELDS
        (
            Z_PK CHAR,
            Z_ENT CHAR,
            Z_OPT CHAR,
            ZADDRESSBOOKID CHAR,
            ZFLAGS CHAR,
            ZINTERNALID CHAR,
            ZPRESENCE CHAR,
            ZTYPE CHAR,
            ZCHATUSER CHAR,
            ZEXTRA CHAR,
            ZLASTMESSAGE CHAR,
            ZDISPLAYNAME CHAR(4000),
            ZDISPLAYNAMEASCII CHAR(4000),
            ZEMAIL CHAR(4000),
            ZFIRSTNAME CHAR(4000),
            ZGROUPTAG CHAR(4000),
            ZJID CHAR(4000),
            ZLASTNAME CHAR(4000),
            ZPPTIMESTAMP CHAR(4000),
            ZPPURL CHAR(4000),
            ZSTATUS CHAR(4000),
            ZUSERNAME CHAR(4000),
            ZCONTENTLINKSPROTODATA CHAR(1048576)
        )
    )
    LOCATION('8e281be6657d4523710d96341b6f86ba89b56df7')
)
NOPARALLEL
NOMONITORING
--REJECT LIMIT 100
;

/*
--test
SELECT *
FROM ZKIKUSER;
*/