SET SERVEROUTPUT ON;
SET TIMING ON;

CREATE OR REPLACE
FUNCTION BOOL_TO_BOOLEAN(gBool IN CHAR)
RETURN BOOLEAN
DETERMINISTIC PARALLEL_ENABLE
AS
    
    PRAGMA UDF;
    
BEGIN
    
    RETURN CASE gBool
        WHEN 'T' THEN TRUE
        WHEN 'F' THEN FALSE
        ELSE NULL
    END;
    
END;
/