SET SERVEROUTPUT ON;
SET TIMING ON;

CREATE OR REPLACE
FUNCTION BOOL_TO_XML(gBool IN CHAR)
RETURN VARCHAR2
DETERMINISTIC PARALLEL_ENABLE
AS
    
    PRAGMA UDF;
    
BEGIN
    
    RETURN CASE gBool
        WHEN 'T' THEN 'true'
        WHEN 'F' THEN 'false'
        ELSE NULL
    END;
    
END;
/