SET SERVEROUTPUT ON;
SET TIMING ON;

CREATE OR REPLACE
FUNCTION DATE_TO_XML(gDate IN DATE)
RETURN VARCHAR2
DETERMINISTIC PARALLEL_ENABLE
AS
    
    PRAGMA UDF;
    
BEGIN
    
    RETURN TO_CHAR(gDate, 'YYYY-MM-DD"T"HH24:MI:SS"Z"');
    
END;
/