CREATE OR REPLACE
FUNCTION GET_TABLE_REFRESH_SOURCE_URL(gTable_Name VARCHAR2)
RETURN TABLESOURCE.SourceURL%TYPE
PARALLEL_ENABLE
AS
    
    PRAGMA UDF;
    
    r TABLESOURCE.SourceURL%TYPE;
    
BEGIN
    
    SELECT SourceURL
    INTO r
    FROM TABLESOURCE AS OF PERIOD FOR VALID_TIME SYS_EXTRACT_UTC(SYSTIMESTAMP)
    WHERE TableLookup_Name = ORACLE_NAME(gTable_Name)
    AND UseInRefreshProcedure = 'T'
    --emulate AS OF PERIOD FOR TRANSACTION_TIME SYS_EXTRACT_UTC(SYSTIMESTAMP)
    AND
    (
        DateTimeDeleted IS NULL
        OR
        DateTimeDeleted > SYS_EXTRACT_UTC(SYSTIMESTAMP)
    );
    
    RETURN r;
    
EXCEPTION
WHEN OTHERS THEN
    
    RETURN NULL;
    
END;
/

/*
--test
SELECT GET_TABLE_REFRESH_SOURCE_URL('MARKET')
FROM DUAL;
*/